//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///   &lt;xsl:output indent=&quot;no&quot; method=&quot;html&quot;/&gt;
        ///
        ///   &lt;xsl:template match=&quot;/&quot;&gt;
        ///      &lt;HTML&gt;
        ///         &lt;HEAD&gt;
        ///            &lt;SCRIPT&gt;
        ///               &lt;xsl:comment&gt;&lt;![CDATA[
        ///                  function f(e){
        ///                     if (e.className==&quot;ci&quot;) {
        ///                       if (e.children(0).innerText.indexOf(&quot;\n&quot;)&gt;0) fix(e,&quot;cb&quot;);
        ///                     }
        ///                     if (e.className==&quot;di&quot;) {
        ///                       if (e.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xs:schema id=&quot;RepDataInfo&quot;
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns=&quot;http://RepDataInfo.xsd&quot;
        ///  targetNamespace=&quot;http://RepDataInfo.xsd&quot;
        ///  version=&quot;1.0&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;Vars&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;varType&quot; type=&quot;varTypeInfo&quot; maxOccurs=&quot;unbounded&quot;/&gt;
        ///      &lt;/xs:sequence&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:element&gt;
        ///
        ///  &lt;xs:complexType  name=&quot;varTypeInfo&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///      &lt;xs:element name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RepDataInfo {
            get {
                return ResourceManager.GetString("RepDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema id=&quot;ReportsInfo.xsd&quot;
        ///  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns=&quot;http://ReportsInfo.xsd&quot;
        ///  targetNamespace=&quot;http://ReportsInfo.xsd&quot;
        ///  version=&quot;1.0&quot;
        ///&gt;
        ///
        ///  &lt;xsd:element name=&quot;Report&quot; type=&quot;reportInfo&quot;/&gt;
        ///
        ///
        ///  &lt;xsd:complexType name=&quot;reportInfo&quot;&gt;
        ///    &lt;xsd:choice maxOccurs=&quot;unbounded&quot;&gt;
        ///      &lt;xsd:element name=&quot;text&quot; type=&quot;textInfo&quot; minOccurs=&quot;0&quot;/&gt;
        ///      &lt;xsd:element name=&quot;img&quot; type=&quot;imgInfo&quot; minOccurs=&quot;0&quot;/&gt;
        ///      &lt;xsd:element name=&quot;check&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportsInfo {
            get {
                return ResourceManager.GetString("ReportsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xs:schema id=&quot;SysAudit&quot;
        ///                  targetNamespace=&quot;http://BO/SysAudit.xsd&quot;
        ///                  xmlns=&quot;http://BO/SysAudit.xsd&quot;
        ///                  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xs:element name=&quot;Audit&quot; type=&quot;SysAuditInfo&quot;/&gt;
        ///  
        ///  &lt;xs:complexType name =&quot;SysAuditInfo&quot;&gt;
        ///    &lt;xs:sequence maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
        ///      &lt;xs:element name=&quot;field&quot; type=&quot;SysAuditFieldInfo&quot;/&gt;
        ///    &lt;/xs:sequence&gt;
        ///    &lt;xs:attribute name=&quot;OperType&quot; type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SysAudit {
            get {
                return ResourceManager.GetString("SysAudit", resourceCulture);
            }
        }
    }
}
