//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace BO.Reports {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ReportsInfo.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Report", Namespace="http://ReportsInfo.xsd", IsNullable=false)]
    public partial class reportInfo {
        
        private itemInfo[] itemsField;
        
        private string nameField;
        
        private System.DateTime modifiedField;
        
        private bool modifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("check", typeof(checkInfo), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("img", typeof(imgInfo), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("text", typeof(textInfo), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public itemInfo[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiedSpecified {
            get {
                return this.modifiedFieldSpecified;
            }
            set {
                this.modifiedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ReportsInfo.xsd")]
    public partial class checkInfo : itemInfo {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(imgInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(checkInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(textInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ReportsInfo.xsd")]
    public abstract partial class itemInfo {
        
        private string groupField;
        
        private float leftField;
        
        private float topField;
        
        private float widthField;
        
        private float heightField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ReportsInfo.xsd")]
    public partial class imgInfo : itemInfo {
        
        private alignType alignField;
        
        private valignType valignField;
        
        private byte[] forecolorField;
        
        private byte[] backcolorField;
        
        private string fontnameField;
        
        private float fontsizeField;
        
        private bool fontboldField;
        
        private bool fontitalicField;
        
        private bool fontunderlineField;
        
        private string srcField;
        
        public imgInfo() {
            this.alignField = alignType.Left;
            this.valignField = valignType.Top;
            this.fontnameField = "Arial";
            this.fontsizeField = ((float)(8F));
            this.fontboldField = false;
            this.fontitalicField = false;
            this.fontunderlineField = false;
            this.srcField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(alignType.Left)]
        public alignType align {
            get {
                return this.alignField;
            }
            set {
                this.alignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(valignType.Top)]
        public valignType valign {
            get {
                return this.valignField;
            }
            set {
                this.valignField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Byte[] is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'hexBinary' is not supported in this version of the .Net Framework.  Ignoring default='000000' attribute.
        [System.Xml.Serialization.XmlAttributeAttribute("fore-color", DataType="hexBinary")]
        public byte[] forecolor {
            get {
                return this.forecolorField;
            }
            set {
                this.forecolorField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Byte[] is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'hexBinary' is not supported in this version of the .Net Framework.  Ignoring default='FFFFFF' attribute.
        [System.Xml.Serialization.XmlAttributeAttribute("back-color", DataType="hexBinary")]
        public byte[] backcolor {
            get {
                return this.backcolorField;
            }
            set {
                this.backcolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-name")]
        [System.ComponentModel.DefaultValueAttribute("Arial")]
        public string fontname {
            get {
                return this.fontnameField;
            }
            set {
                this.fontnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-size")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "8")]
        public float fontsize {
            get {
                return this.fontsizeField;
            }
            set {
                this.fontsizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-bold")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fontbold {
            get {
                return this.fontboldField;
            }
            set {
                this.fontboldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-italic")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fontitalic {
            get {
                return this.fontitalicField;
            }
            set {
                this.fontitalicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-underline")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fontunderline {
            get {
                return this.fontunderlineField;
            }
            set {
                this.fontunderlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ReportsInfo.xsd")]
    public enum alignType {
        
        /// <remarks/>
        Left,
        
        /// <remarks/>
        Center,
        
        /// <remarks/>
        Right,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ReportsInfo.xsd")]
    public enum valignType {
        
        /// <remarks/>
        Top,
        
        /// <remarks/>
        Center,
        
        /// <remarks/>
        Bottom,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ReportsInfo.xsd")]
    public partial class textInfo : itemInfo {
        
        private alignType alignField;
        
        private valignType valignField;
        
        private byte[] forecolorField;
        
        private byte[] backcolorField;
        
        private string fontnameField;
        
        private float fontsizeField;
        
        private bool fontboldField;
        
        private bool fontitalicField;
        
        private bool fontunderlineField;
        
        private bool nowrapField;
        
        private float[] borderField;
        
        private byte[][] bordercolorField;
        
        public textInfo() {
            this.fontnameField = "Arial";
            this.fontsizeField = ((float)(8F));
            this.fontboldField = false;
            this.fontitalicField = false;
            this.fontunderlineField = false;
            this.nowrapField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public alignType align {
            get {
                return this.alignField;
            }
            set {
                this.alignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public valignType valign {
            get {
                return this.valignField;
            }
            set {
                this.valignField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Byte[] is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'hexBinary' is not supported in this version of the .Net Framework.  Ignoring default='000000' attribute.
        [System.Xml.Serialization.XmlAttributeAttribute("fore-color", DataType="hexBinary")]
        public byte[] forecolor {
            get {
                return this.forecolorField;
            }
            set {
                this.forecolorField = value;
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Byte[] is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'hexBinary' is not supported in this version of the .Net Framework.  Ignoring default='FFFFFF' attribute.
        [System.Xml.Serialization.XmlAttributeAttribute("back-color", DataType="hexBinary")]
        public byte[] backcolor {
            get {
                return this.backcolorField;
            }
            set {
                this.backcolorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-name")]
        [System.ComponentModel.DefaultValueAttribute("Arial")]
        public string fontname {
            get {
                return this.fontnameField;
            }
            set {
                this.fontnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-size")]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "8")]
        public float fontsize {
            get {
                return this.fontsizeField;
            }
            set {
                this.fontsizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-bold")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fontbold {
            get {
                return this.fontboldField;
            }
            set {
                this.fontboldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-italic")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fontitalic {
            get {
                return this.fontitalicField;
            }
            set {
                this.fontitalicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("font-underline")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fontunderline {
            get {
                return this.fontunderlineField;
            }
            set {
                this.fontunderlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("no-wrap")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool nowrap {
            get {
                return this.nowrapField;
            }
            set {
                this.nowrapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float[] border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("border-color", DataType="hexBinary")]
        public byte[][] bordercolor {
            get {
                return this.bordercolorField;
            }
            set {
                this.bordercolorField = value;
            }
        }
    }
}
